### ISSUE TITLE
Image style not working

### ISSUE THREAD

**Issue by simone960** [backdrop-contrib/image_url_formatter#1]
It doesn't seem to support image style or at least not working properly. Example, when I select image style "Medium (300x250)", the image url not really showing the path to the medium (300x250) image thumbnail but instead showing the original image path where it is first uploaded. Any idea ?

**Comment by opi** [comment]
Thanks for reporting this bug, I confirm the behavior.

I created a quick pull-request to solve this https://github.com/backdrop-contrib/image_url_formatter/pull/2 ; @Graham-72 can you review & test it please ? 

Thanks !

**Comment by Graham-72** [comment]
@opi thank you for this. I have done some testing and this is a big improvement but I have found there are still some problems.

Of the four options for the URL type, the first (URI path) is not showing a path to a 'styled' image. Only the fourth (Full URL) is producing a result that works in my test installation, but that may be a result of the way that is configured.

Also, if you choose the option to link the Image URL to the file, it links to the original image and not the styled version, and if using the URI Path option it is not linked to anything.

Have you time to look at this again please? I will try and do some more testing in a different site.

**Comment by simone960** [comment]
Thanks for looking into it. Hopefully this can be fixed soon. I am using it to create a parallax scrolling effect with the background images. This module is pretty handy.

**Comment by opi** [comment]
Updated PR with a fix for derivative (aka image style) URI path.

This diff is hard to read, perhaps it's easier to look at the `theme_image_url_formatter` function https://github.com/backdrop-contrib/image_url_formatter/blob/9340d4b69d84c76a7042c07699bc4e8bcf15a582/image_url_formatter.module#L198-L234
