### ISSUE TITLE
Why this formatter is available on file fields ?

### ISSUE THREAD

**Issue by opi** [backdrop-contrib/image_url_formatter#4]
https://github.com/backdrop-contrib/image_url_formatter/blob/1.x-1.x/image_url_formatter.module#L39

Not sure this is useful, and could lead to strange edge case (generate image style path for a basic file field won't work).

What about removing the "file" field type ?

**Comment by Graham-72** [comment]
@opi yes, I agree. I will remove "file" field type.
Apologies for delay in responding to your comment.

**Comment by Graham-72** [comment]
Fixed by pull request #7
