### ISSUE TITLE
Notice: Undefined index: type in theme_image_url_formatter() (line 213

### ISSUE THREAD

**Issue by simone960** [backdrop-contrib/image_url_formatter#5]
I noticed there are errors generated in the **recent log messages** whenever I visited those pages using the module. Any idea?

`Notice: Undefined index: type in theme_image_url_formatter() (line 213 of ...../modules/image_url_formatter/image_url_formatter.module).`

**Comment by opi** [comment]
Are you using the last 1.4.1 version ?

**Comment by simone960** [comment]
Ops... I was using 1.4.0... 

Ok, just upgraded to 1.4.1 version now and the errors no longer produced !  Just noticed the image style also fixed, I can see the right path pointed to the image style I selected. Thanks @opi ! You are awesome !!
